### ISSUE TITLE
Item is NoneType

### ISSUE THREAD

**Issue by yiiiiieah** [tvgrabbers/DataTree#1]
```
(...)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/DataTreeGrab.py", line 3169, in link_functions
    if item.lower() in sitem.keys():
AttributeError: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/DataTreeGrab.py", line 3169, in link_functions
    if item.lower() in sitem.keys():
AttributeError: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/DataTreeGrab.py", line 3169, in link_functions
    if item.lower() in sitem.keys():
AttributeError: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/DataTreeGrab.py", line 3169, in link_functions
    if item.lower() in sitem.keys():
AttributeError: 'NoneType' object has no attribute 'lower'
(...)
```

Maybe add a check whether item is None?

**Comment by hikavdh** [comment]
True, it now is caught by a general try except loop, so no harm done. Will do in the next release. You might by the way want to upgrade. The recent release is potentially significantly faster. A next release is expected in a month or so.
